#!/usr/bin/zsh
KEY=$(cat ../../se-api-key)
lwp-request "https://monitoringapi.solaredge.com/site/3045847/energyDetails?timeUnit=MONTH&startTime=2022-01-01%2000:00:00&endTime=2022-12-31%2000:00:00&api_key=$KEY"
